#pragma once

#define auto_cache(key, name) \
struct name##Cache { \
	std::vector<name> data; \
}; \
template <> \
struct glz::meta<name##Cache> { \
using T = name##Cache; \
constexpr static auto value = object(key, &T::data); \
};

auto_cache("bD18x9Ti", LoginCampaignReward)
auto_cache("YDv9bJ3s", UserLevelMst)
auto_cache("KeC10fuL", VersionInfo)
auto_cache("Lh1I3dGo", TownFacilityMst)
auto_cache("d0EkJ4TB", TownFacilityLvMst)
auto_cache("1y2JDv79", TownLocationMst)
auto_cache("9ekQ4tZq", TownLocationLvMst)
auto_cache("hV5vWu6C", NpcMst)
auto_cache("Pk5F1vhx", BannerInfoMst)
auto_cache("z5U7utsm", ExtraPassiveSkillMst)
auto_cache("a739yK18", DailyTaskPrizeMst)
auto_cache("k23D7d43", DailyTaskMst)
auto_cache("4NG79sX1", DungeonKeyMst)
auto_cache("6kWq78zx", ArenaRankMst)
auto_cache("Pf97SzVw", GachaEffectMst)
auto_cache("5Y4GJeo3", GachaMst)
auto_cache("IBs49NiH", GachaCategory)
auto_cache("bpD29eiQ", VideoAdRegion)
auto_cache("j129kD6r", VideoAdInfo)
auto_cache("1IR86sAv", GachaInfoMst)
auto_cache("3aDk1xk7", ExcludedDungeonMissionMst)
// Loaded only to build ServerCache's dungeon -> missions index; the rows are
// discarded afterwards.  See ServerCache::missionsByDungeon().
auto_cache("oXeC1Ak9", MissionMst)
auto_cache("JYFGe9y6", UnitExpPatternMst)
auto_cache("8f0bCciN", ReceipeMst)
auto_cache("6CTU8m2v", TrophyMst)
auto_cache("1NTG2oVZ", TrophyGroupMst)
auto_cache("Ked15IpH", TrophyGradeMst)
auto_cache("5nBa3CAe", InformationMst)
auto_cache("9x4zZCeN", HelpMst)
auto_cache("At7Gny2V", UrlMst)
auto_cache("mQC4s5ka", ChallengeMst)
auto_cache("h09mEvDR", ChallengeHrMst)
auto_cache("5M8jI4cP", ChallengeMisMst)
auto_cache("zW1i02aG", ChallengeGradeMst)
auto_cache("4C1Wt8sS", ChallengeRewardMst)
auto_cache("dn0NfRy1", ChallengeItemMst)
auto_cache("B8lchAPr", InteractiveBannerInfoMst)
auto_cache("36Sd0Aub", SoundMst)
auto_cache("Bm1WNDQ0", GiftItemMst)
auto_cache("Md9gG3c0", GeneralEventMst)
auto_cache("8UawtzHw", FirstDescMst)
auto_cache("hE1d083b", SummonTicketV2Mst)
auto_cache("da3qD39b", ResummonGachaMst)
auto_cache("5C9LuNrk", HelpSubMst)
auto_cache("P8V71kbw", ChallengeRankRewardMst)
auto_cache("nUmaEC41", ChallengeMvpMst)
auto_cache("2r9cNSdt", UnitMst)
auto_cache("2C7LDzYk", ItemMst)
auto_cache("as8G75gK", GrandMissionMst)
auto_cache("iyCP4N1h", GrandMissionMapMst)
auto_cache("aqb6LS9y", GrandMissionSpotMst)
auto_cache("Ri1S0JQX", GrandMissionRouteMst)
auto_cache("HUo5G8gz", GrandMissionIconMst)
auto_cache("hpGBs2R1", GrandMissionTreasureMst)
auto_cache("27tgwCUN", GrandMissionFlgMst)
auto_cache("0sT4d2zV", GrandMissionEndCndMst)
auto_cache("x3kCNR4Y", GrandMissionEventMst)
auto_cache("Q83eyrJM", GrandMissionRewardMst)
auto_cache("S9zI8iPU", RaidWorldMst)
auto_cache("K3H0uzhE", RaidMapMst)
auto_cache("Yr5PCpo3", RaidRcMst)
auto_cache("n2kNWdq5", RaidPlaystyleMst)
auto_cache("0qK4FXpC", RaidBossMst)
auto_cache("VyDP51hx", RaidBossRouteMst)
auto_cache("8J0dh4YZ", RaidMissionMst)
auto_cache("7pJD5tNd", RaidMissionBossMst)
auto_cache("9EmPTqn3", RaidMissionClearCndMst)
auto_cache("6hLn3bBr", RaidMissionPointMst)
auto_cache("4XA9m7of", RaidPointMst)
auto_cache("maU6riN7", RaidUserRouteMst)
auto_cache("QEv8VG6C", RaidBattleGroupMst)
auto_cache("wmpLokaR", ColosseumClassMst)
auto_cache("iG9H7mHS", ColosseumExtraRuleMst)
auto_cache("aCmTmaOx", ColosseumFormationMst)
auto_cache("kaQtidz4", ColosseumSupportMst)
auto_cache("fTV3A0By", DbbMst)
auto_cache("keTrog0p", DbbBondRecipeMst)
auto_cache("p3bDi1jq", GuildInfoMst)
auto_cache("fDLao3cs", GuildMemberSkillMst)
auto_cache("baD81eqw", GuildPointExchangeMst)
auto_cache("UVz5cuZ4", PurchaseAgeLimitMst)
auto_cache("olzMKWSZ", FrontierGateMst)
auto_cache("uxpnA5rF", FrontierGateSupportMst)
auto_cache("aYcBePEP", SummonerAbilityMst)
auto_cache("6XHRamCn", SummonerAbilityLevelMst)
auto_cache("xUo0D9Xb", SummonerAbilityUpMst)
auto_cache("JuBeb6YR", SummonerArmMst)
auto_cache("kgaeVEzx", SummonerArmElementMst)
auto_cache("eKPdSFdy", SummonerElementLevelMst)
auto_cache("cq1n3Nfy", SummonerExSkillMst)
auto_cache("BbmQBxhV", SummonerImageMst)
auto_cache("LRB9Z5zm", SummonerLevelMst)
auto_cache("8aiBoHg5", SkillMst)
auto_cache("3ktU0D2e", SkillLevelMst)
auto_cache("2bGtP7vV", LeaderSkillMst)
auto_cache("yY3Mvp51", UnitEvoMst)
auto_cache("K4d9sl4s", UnitEvoOmniMst)
auto_cache("34d0Slkf", UnitEvoOmniTypeMst)
auto_cache("Odks40sl", UnitEvoOmniRecipeMst)
auto_cache("LBY10TPU", UnitTypeMst)
auto_cache("0H1hV6iD", UnitExtMst)
auto_cache("XFD1gtfo", UnitEp3Mst)
auto_cache("07bx6EXN", UnitCgsMst)
auto_cache("gkVH5p8r", UnitCommentMst)
auto_cache("kXes8fSi", UnitFeSkillMst)
auto_cache("kvSPgNAk", UnitFeCategoryMst)
auto_cache("vE0Qdg33", MissionEp3Mst)
auto_cache("uYHZWC73", GateMst)
auto_cache("3SG2wX0R", AreaMst)
auto_cache("01pzrTCm", DungeonMst)
auto_cache("5DXlaudE", ShopItemMst)
auto_cache("GHUsyi76", MedalMst)
auto_cache("a3IgzZ0q", HelpDetailMst)
auto_cache("KFJBwYbR", PvpFixedSettingMst)

// Local-only cache declarations, if this checkout has any.  Keeps dev-fork
// tables out of this file so they don't collide with upstream edits.
// After ADDING the file, touch this header: when it was absent nothing
// recorded a dependency on it, so the build won't otherwise notice.
#if __has_include("ServerCacheLocalMst.inl")
	#include "ServerCacheLocalMst.inl"
#endif
